// Global

export const CHANGE_IS_SUBMITTING = "CHANGE_IS_SUBMITTING"
export const CHANGE_LANDINGTEXT = "CHANGE_LANDINGTEXT"
export const CHANGE_IS_FORM_TEXT = "CHANGE_IS_FORM_TEXT"
export const CHANGE_IS_ERROR = "CHANGE_IS_ERROR"
